In [1]:
import pandas as pd
df = pd.read_csv("C:\\Users\\saipr\\BigBasket\\data\\BigBasket Products.csv")

In [2]:
df

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.00,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.00,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.00,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.00,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.00,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...
...,...,...,...,...,...,...,...,...,...,...
27550,27551,"Wottagirl! Perfume Spray - Heaven, Classic",Beauty & Hygiene,Fragrances & Deos,Layerr,199.20,249.0,Perfume,3.9,Layerr brings you Wottagirl Classic fragrant b...
27551,27552,Rosemary,Gourmet & World Food,Cooking & Baking Needs,Puramate,67.50,75.0,"Herbs, Seasonings & Rubs",4.0,Puramate rosemary is enough to transform a dis...
27552,27553,Peri-Peri Sweet Potato Chips,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",FabBox,200.00,200.0,Nachos & Chips,3.8,We have taken the richness of Sweet Potatoes (...
27553,27554,Green Tea - Pure Original,Beverages,Tea,Tetley,396.00,495.0,Tea Bags,4.2,"Tetley Green Tea with its refreshing pure, ori..."
27554,27555,United Dreams Go Far Deodorant,Beauty & Hygiene,Men's Grooming,United Colors Of Benetton,214.53,390.0,Men's Deodorants,4.5,The new mens fragrance from the United Dreams ...

In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

target = "category"

df["text"] = (
    df["product"].fillna("") + " " +
    df["brand"].fillna("") + " " +
    df["type"].fillna("") + " " +
    df["description"].fillna("")
)

X = df["text"]
y = df[target]

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [22]:
pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=20000,   # limit features for speed
        ngram_range=(1,2),    # unigrams + bigrams
        stop_words="english"
    )),
    ("clf", LogisticRegression(class_weight="balanced"))
])

In [23]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=20000, ngram_range=(1, 2),
                                 stop_words='english')),
                ('clf', LogisticRegression(class_weight='balanced'))])

In [24]:
y_pred = pipeline.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9678824169842134

Classification Report:
                           precision    recall  f1-score   support

               Baby Care       0.91      0.96      0.93       122
   Bakery, Cakes & Dairy       0.91      0.99      0.95       170
        Beauty & Hygiene       0.99      0.98      0.98      1574
               Beverages       0.87      0.99      0.93       177
    Cleaning & Household       0.97      0.99      0.98       535
       Eggs, Meat & Fish       0.97      1.00      0.99        70
Foodgrains, Oil & Masala       0.95      0.96      0.95       535
     Fruits & Vegetables       0.98      1.00      0.99       111
    Gourmet & World Food       0.96      0.92      0.94       938
  Kitchen, Garden & Pets       1.00      0.98      0.99       716
  Snacks & Branded Foods       0.97      0.96      0.96       563

                accuracy                           0.97      5511
               macro avg       0.95      0.98      0.96      5511
            weighted avg       0.97      0.97      0.97      5511

In [25]:
from sklearn.ensemble import RandomForestClassifier
pipeline1 = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=20000,   # limit features for speed
        ngram_range=(1,2),    # unigrams + bigrams
        stop_words="english"
    )),
    ("clf", RandomForestClassifier())
])

In [26]:
pipeline1.fit(X_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=20000, ngram_range=(1, 2),
                                 stop_words='english')),
                ('clf', RandomForestClassifier())])

In [27]:
y_pred = pipeline1.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9673380511703865

Classification Report:
                           precision    recall  f1-score   support

               Baby Care       0.97      0.93      0.95       122
   Bakery, Cakes & Dairy       0.99      0.88      0.93       170
        Beauty & Hygiene       0.97      1.00      0.98      1574
               Beverages       0.98      0.92      0.95       177
    Cleaning & Household       0.98      0.96      0.97       535
       Eggs, Meat & Fish       0.99      0.94      0.96        70
Foodgrains, Oil & Masala       0.97      0.95      0.96       535
     Fruits & Vegetables       0.98      0.96      0.97       111
    Gourmet & World Food       0.94      0.97      0.95       938
  Kitchen, Garden & Pets       0.99      0.98      0.99       716
  Snacks & Branded Foods       0.97      0.94      0.95       563

                accuracy                           0.97      5511
               macro avg       0.97      0.95      0.96      5511
            weighted avg       0.97      0.97      0.97      5511

In [28]:
from sklearn.svm import SVC
pipeline2 = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=20000,   # limit features for speed
        ngram_range=(1,2),    # unigrams + bigrams
        stop_words="english"
    )),
    ("clf", SVC())
])

In [29]:
pipeline2.fit(X_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=20000, ngram_range=(1, 2),
                                 stop_words='english')),
                ('clf', SVC())])

In [30]:
y_pred = pipeline2.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9785882779894756

Classification Report:
                           precision    recall  f1-score   support

               Baby Care       0.95      0.94      0.95       122
   Bakery, Cakes & Dairy       0.98      0.95      0.96       170
        Beauty & Hygiene       0.98      0.99      0.99      1574
               Beverages       0.98      0.97      0.97       177
    Cleaning & Household       0.99      0.98      0.99       535
       Eggs, Meat & Fish       1.00      1.00      1.00        70
Foodgrains, Oil & Masala       0.97      0.96      0.96       535
     Fruits & Vegetables       0.98      0.97      0.98       111
    Gourmet & World Food       0.95      0.98      0.96       938
  Kitchen, Garden & Pets       1.00      0.99      0.99       716
  Snacks & Branded Foods       0.99      0.96      0.97       563

                accuracy                           0.98      5511
               macro avg       0.98      0.97      0.98      5511
            weighted avg       0.98      0.98      0.98      5511

In [32]:
from sklearn.naive_bayes import MultinomialNB
pipeline4 = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=20000,   
        ngram_range=(1,2),    
        stop_words="english"
    )),
    ("clf", MultinomialNB())
])
pipeline4.fit(X_train, y_train)
y_pred = pipeline4.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8980221375430957

Classification Report:
                           precision    recall  f1-score   support

               Baby Care       0.96      0.62      0.76       122
   Bakery, Cakes & Dairy       1.00      0.36      0.53       170
        Beauty & Hygiene       0.94      0.99      0.97      1574
               Beverages       1.00      0.28      0.43       177
    Cleaning & Household       0.97      0.95      0.96       535
       Eggs, Meat & Fish       1.00      0.63      0.77        70
Foodgrains, Oil & Masala       0.94      0.90      0.92       535
     Fruits & Vegetables       0.98      0.85      0.91       111
    Gourmet & World Food       0.72      0.97      0.82       938
  Kitchen, Garden & Pets       0.97      0.97      0.97       716
  Snacks & Branded Foods       0.92      0.85      0.88       563

                accuracy                           0.90      5511
               macro avg       0.95      0.76      0.81      5511
            weighted avg       0.91      0.90      0.89      5511

In [ ]:
# Predict category
new_query = "Do you have fresh chicken or eggs?"

predicted_category = pipeline1.predict([new_query])[0]
print("Predicted Category:", predicted_category)

In [ ]:
# Predict category
predicted_category = pipeline2.predict([new_query])[0]
print("Predicted Category:", predicted_category)

RAG with FAISS

In [1]:
import pandas as pd 
df = pd.read_csv("C:\\Users\\saipr\\BigBasket\data\\BigBasket Products.csv")

In [2]:
df

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.00,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.00,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.00,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.00,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.00,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...
...,...,...,...,...,...,...,...,...,...,...
27550,27551,"Wottagirl! Perfume Spray - Heaven, Classic",Beauty & Hygiene,Fragrances & Deos,Layerr,199.20,249.0,Perfume,3.9,Layerr brings you Wottagirl Classic fragrant b...
27551,27552,Rosemary,Gourmet & World Food,Cooking & Baking Needs,Puramate,67.50,75.0,"Herbs, Seasonings & Rubs",4.0,Puramate rosemary is enough to transform a dis...
27552,27553,Peri-Peri Sweet Potato Chips,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",FabBox,200.00,200.0,Nachos & Chips,3.8,We have taken the richness of Sweet Potatoes (...
27553,27554,Green Tea - Pure Original,Beverages,Tea,Tetley,396.00,495.0,Tea Bags,4.2,"Tetley Green Tea with its refreshing pure, ori..."
27554,27555,United Dreams Go Far Deodorant,Beauty & Hygiene,Men's Grooming,United Colors Of Benetton,214.53,390.0,Men's Deodorants,4.5,The new mens fragrance from the United Dreams ...

In [7]:
import logging
import pandas as pd
from langchain_core.documents import Document


def prepare_documents(df: pd.DataFrame) -> list[Document]:
    df = df.copy()

    essential_cols = ["product", "description", "sale_price", "market_price", "rating"]
    df.dropna(subset=essential_cols, inplace=True)

    numeric_cols = ["sale_price", "market_price", "rating"]
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    df.dropna(subset=numeric_cols, inplace=True)

    if "category" in df.columns and "sub_category" in df.columns:
        df["category_tag"] = df["category"] + " > " + df["sub_category"]
    else:
        df["category_tag"] = "Unknown"

    documents = []
    for _, row in df.iterrows():
        text = (
            f"Product: {row['product']}\n"
            f"Brand: {row.get('brand', 'Unknown')}\n"
            f"Category: {row['category_tag']}\n"
            f"Type: {row.get('type', 'Unknown')}\n"
            f"Sale Price: ₹{row['sale_price']}\n"
            f"Market Price: ₹{row['market_price']}\n"
            f"Rating: {row['rating']} / 5.0\n"
            f"Description: {row['description']}"
        )

        metadata = {
            "product": row["product"],
            "brand": row.get("brand", "Unknown"),
            "category": row.get("category", "Unknown"),
            "sub_category": row.get("sub_category", "Unknown"),
            "type": row.get("type", "Unknown"),
            "sale_price": float(row["sale_price"]),
            "market_price": float(row["market_price"]),
            "rating": float(row["rating"]),
            "category_tag": row["category_tag"]
        }

        documents.append(Document(page_content=text, metadata=metadata))

    return documents

In [8]:
docs=prepare_documents(df)

In [9]:
docs

[Document(metadata={'product': 'Garlic Oil - Vegetarian Capsule 500 mg', 'brand': 'Sri Sri Ayurveda ', 'category': 'Beauty & Hygiene', 'sub_category': 'Hair Care', 'type': 'Hair Oil & Serum', 'sale_price': 220.0, 'market_price': 220.0, 'rating': 4.1, 'category_tag': 'Beauty & Hygiene > Hair Care'}, page_content='Product: Garlic Oil - Vegetarian Capsule 500 mg\nBrand: Sri Sri Ayurveda \nCategory: Beauty & Hygiene > Hair Care\nType: Hair Oil & Serum\nSale Price: ₹220.0\nMarket Price: ₹220.0\nRating: 4.1 / 5.0\nDescription: This Product contains Garlic Oil that is known to help proper digestion, maintain proper cholesterol levels, support cardiovascular and also build immunity.  For Beauty tips, tricks & more visit https://bigbasket.blog/'),
 Document(metadata={'product': 'Water Bottle - Orange', 'brand': 'Mastercook', 'category': 'Kitchen, Garden & Pets', 'sub_category': 'Storage & Accessories', 'type': 'Water & Fridge Bottles', 'sale_price': 180.0, 'market_price': 180.0, 'rating': 2.3, 'category_tag': 'Kitchen, Garden & Pets > Storage & Accessories'}, page_content='Product: Water Bottle - Orange\nBrand: Mastercook\nCategory: Kitchen, Garden & Pets > Storage & Accessories\nType: Water & Fridge Bottles\nSale Price: ₹180.0\nMarket Price: ₹180.0\nRating: 2.3 / 5.0\nDescription: Each product is microwave safe (without lid), refrigerator safe, dishwasher safe and can also be used for re-heating food and not for cooking. All containers come with airtight lids and a wide variety of attractive colours. Stack these stylish and colourful containers in your kitchen with ease and for a look-good factor.'),
 Document(metadata={'product': 'Brass Angle Deep - Plain, No.2', 'brand': 'Trm', 'category': 'Cleaning & Household', 'sub_category': 'Pooja Needs', 'type': 'Lamp & Lamp Oil', 'sale_price': 119.0, 'market_price': 250.0, 'rating': 3.4, 'category_tag': 'Cleaning & Household > Pooja Needs'}, page_content='Product: Brass Angle Deep - Plain, No.2\nBrand: Trm\nCategory: Cleaning & Household > Pooja Needs\nType: Lamp & Lamp Oil\nSale Price: ₹119.0\nMarket Price: ₹250.0\nRating: 3.4 / 5.0\nDescription: A perfect gift for all occasions, be it your mother, sister, in-laws, boss or your friends, this beautiful designer piece wherever placed, is sure to beautify the surroundings Traditional design This type diya has been used for Diwali and All other Festivals for centuries. Sturdy and easy to carry The feet keep it balanced to ensure safety. Wonderful Oil Lamp made in Brass also called as Jyoti. This is a handcrafted piece of Indian brass Deepak.'),
 Document(metadata={'product': 'Cereal Flip Lid Container/Storage Jar - Assorted Colour', 'brand': 'Nakoda', 'category': 'Cleaning & Household', 'sub_category': 'Bins & Bathroom Ware', 'type': 'Laundry, Storage Baskets', 'sale_price': 149.0, 'market_price': 176.0, 'rating': 3.7, 'category_tag': 'Cleaning & Household > Bins & Bathroom Ware'}, page_content='Product: Cereal Flip Lid Container/Storage Jar - Assorted Colour\nBrand: Nakoda\nCategory: Cleaning & Household > Bins & Bathroom Ware\nType: Laundry, Storage Baskets\nSale Price: ₹149.0\nMarket Price: ₹176.0\nRating: 3.7 / 5.0\nDescription: Multipurpose container with an attractive design and made from food-grade plastic for your hygiene and safety ideal for storing pulses. Grains, spices, and more with easy opening and closing flip-open lid. Strong, durable and transparent body for longevity and easy identification of contents. Multipurpose storage solution for your daily needs stores your everyday food essentials in style with the Nakoda container set. With transparent bodies, you can easily identify your stored items without having to open the lids. These containers are ideal for storing a large variety of items such as food grains, snacks and pulses to sugar, spices, condiments and more. Featuring unique flip-open lids, you can easily open and close this container without any hassles.\nThe Nakoda container is made from high-quality food-grade and BPA-free plastic that is 100% safe for storing food items. You can safely store your food items in this container without worrying about contamination and harmful toxins. As they are constructed using highly durable virgin plastic, this container will last for a long time even with regular use. This container can enhance the overall look of your kitchen decor. Being dishwasher safe, cleaning and maintaining this container is an easy task. You can also use a simple soap solution to manually wash and retain their looks for a long time.'),
 Document(metadata={'product': 'Creme Soft Soap - For Hands & Body', 'brand': 'Nivea', 'category': 'Beauty & Hygiene', 'sub_category': 'Bath & Hand Wash', 'type': 'Bathing Bars & Soaps', 'sale_price': 162.0, 'market_price': 162.0, 'rating': 4.4, 'category_tag': 'Beauty & Hygiene > Bath & Hand Wash'}, page_content='Product: Creme Soft Soap - For Hands & Body\nBrand: Nivea\nCategory: Beauty & Hygiene > Bath & Hand Wash\nType: Bathing Bars & Soaps\nSale Price: ₹162.0\nMarket Price: ₹162.0\nRating: 4.4 / 5.0\nDescription: Nivea Creme Soft Soap gives your skin the best care that it must get. The soft bar consists of Vitamins F and Almonds which are really skin gracious and help you get great skin. It provides the skin with moisture and leaves behind flawless and smooth skin. It makes sure that your body is totally free of germs & dirt and at the same time well nourished.For Beauty tips, tricks & more visit https://bigbasket.blog/'),
 Document(metadata={'product': 'Germ - Removal Multipurpose Wipes', 'brand': 'Nature Protect', 'category': 'Cleaning & Household', 'sub_category': 'All Purpose Cleaners', 'type': 'Disinfectant Spray & Cleaners', 'sale_price': 169.0, 'market_price': 199.0, 'rating': 3.3, 'category_tag': 'Cleaning & Household > All Purpose Cleaners'}, page_content='Product: Germ - Removal Multipurpose Wipes\nBrand: Nature Protect\nCategory: Cleaning & Household > All Purpose Cleaners\nType: Disinfectant Spray & Cleaners\nSale Price: ₹169.0\nMarket Price: ₹199.0\nRating: 3.3 / 5.0\nDescription: Stay protected from contamination with Multipurpose Germ Removal Wipes by Nature Protect, a quality product by Hindustan Unilever Limited, the makers of Surf Excel and Lifebuoy. Infused with neem extract Nature Protect Multipurpose Germ removal wipes helps in cleaning and 99.9% germ removal^. Neem extracts are known to have the power of 100 bio-actives with both anti-viral and anti-bacterial capabilities.\nWipes made from 100% biodegradable fabric and balanced with skin’s pH level, our on-the-go hygiene wipes are safe to use on not just surfaces, but human skin, so you can disinfect any exposed parts of your body – such as your hands, elbows, or wrists – as well as the surfaces they’ve touched.\xa0 A thorough cleaning with on-the-go hygiene wipes helps in keeping surfaces hygienically clean, both inside and outside your home. Packaged neatly to enable quick, easy removal, these on-the-go hygiene wipes will help you stay protected whether you stay indoors or move out and about.\n^ As per lab test conducted on representative organisms.* Always spot test on hidden area to check compatibility.'),
 Document(metadata={'product': 'Multani Mati', 'brand': 'Satinance', 'category': 'Beauty & Hygiene', 'sub_category': 'Skin Care', 'type': 'Face Care', 'sale_price': 58.0, 'market_price': 58.0, 'rating': 3.6, 'category_tag': 'Beauty & Hygiene > Skin Care'}, page_content='Product: Multani Mati\nBrand: Satinance\nCategory: Beauty & Hygiene > Skin Care\nType: Face Care\nSale Price: ₹58.0\nMarket Price: ₹58.0\nRating: 3.6 / 5.0\nDescription: Satinance multani matti is an excellent skin toner and astringent. reduces oiliness and while nourishing the skin, keeps it soft and grime. improves complexion by facilitating better blood circulation.  For Beauty tips, tricks & more visit https://bigbasket.blog/'),
 Document(metadata={'product': 'Hand Sanitizer - 70% Alcohol Base', 'brand': 'Bionova', 'category': 'Beauty & Hygiene', 'sub_category': 'Bath & Hand Wash', 'type': 'Hand Wash & Sanitizers', 'sale_price': 250.0, 'market_price': 250.0, 'rating': 4.0, 'category_tag': 'Beauty & Hygiene > Bath & Hand Wash'}, page_content='Product: Hand Sanitizer - 70% Alcohol Base\nBrand: Bionova\nCategory: Beauty & Hygiene > Bath & Hand Wash\nType: Hand Wash & Sanitizers\nSale Price: ₹250.0\nMarket Price: ₹250.0\nRating: 4.0 / 5.0\nDescription: 70%Alcohol based is gentle of hand leaves skin soft and moist with a good fragrance. It is really safe for the skin.'),
 Document(metadata={'product': 'Biotin & Collagen Volumizing Hair Shampoo + Biotin & Collagen Hair Conditioner', 'brand': 'StBotanica', 'category': 'Beauty & Hygiene', 'sub_category': 'Hair Care', 'type': 'Shampoo & Conditioner', 'sale_price': 1098.0, 'market_price': 1098.0, 'rating': 3.5, 'category_tag': 'Beauty & Hygiene > Hair Care'}, page_content='Product: Biotin & Collagen Volumizing Hair Shampoo + Biotin & Collagen Hair Conditioner\nBrand: StBotanica\nCategory: Beauty & Hygiene > Hair Care\nType: Shampoo & Conditioner\nSale Price: ₹1098.0\nMarket Price: ₹1098.0\nRating: 3.5 / 5.0\nDescription: An exclusive blend with Vitamin B7 Biotin, Hydrolyzed collagen, Oat Extract along with premium & organic cold-pressed ingredients helps to infuse nutrients into every strand and creates the appearance of thicker, fuller healthier looking hair. This powerful formula helps volumize even the skinniest strands into fuller and more abundant looking locks. It is safe for color-treated hair and safe for all hair types. St Botanica Biotin & Collagen Hair Conditioner has been specially formulated to repair dry & damaged hair for full, thick, voluminous, shiny & healthy looking hair! The amazing hair conditioner ingredients include Biotin, Hydrolyzed Collagen, Pro-Vitamin B5, Vitamin E, & Hydrolyzed Silk Proteins for glistening looking hair. Biotin and Collagen, infused with most efficacious natural extracts not only promotes healthy hair growth but also prevents hair dryness, increases the elasticity of the hair cortex, thereby strengthening hair, minimizing hair breakage and helping hair grow longer, healthier and thicker. PLUMP IT UP: the nutrient-rich, plump-it-up power of this haircare infused with ProVitamin B7 biotin and collagen helps give each strand of hair a beautiful boost, this dynamic duo will leave your hair feeling thicker, fuller, and looking oh, so healthy.'),
 Document(metadata={'product': 'Scrub Pad - Anti- Bacterial, Regular', 'brand': 'Scotch brite', 'category': 'Cleaning & Household', 'sub_category': 'Mops, Brushes & Scrubs', 'type': 'Utensil Scrub-Pad, Glove', 'sale_price': 20.0, 'market_price': 20.0, 'rating': 4.3, 'category_tag': 'Cleaning & Household > Mops, Brushes & Scrubs'}, page_content='Product: Scrub Pad - Anti- Bacterial, Regular\nBrand: Scotch brite\nCategory: Cleaning & Household > Mops, Brushes & Scrubs\nType: Utensil Scrub-Pad, Glove\nSale Price: ₹20.0\nMarket Price: ₹20.0\nRating: 4.3 / 5.0\nDescription: Scotch Brite Anti- Bacterial Scrub Pad thoroughly cleanses dishes and keeps the kitchen utensils squeaky clean with a pleasant neem fragrance. The scrub is gentle on the hands and does not wear off easily, while eliminating bacteria and making your utensils sparkle and look as good as new with every wash.'),
 Document(metadata={'product': 'Wheat Grass Powder - Raw', 'brand': 'NUTRASHIL', 'category': 'Gourmet & World Food', 'sub_category': 'Cooking & Baking Needs', 'type': 'Flours & Pre-Mixes', 'sale_price': 261.0, 'market_price': 290.0, 'rating': 4.0, 'category_tag': 'Gourmet & World Food > Cooking & Baking Needs'}, page_content='Product: Wheat Grass Powder - Raw\nBrand: NUTRASHIL\nCategory: Gourmet & World Food > Cooking & Baking Needs\nType: Flours & Pre-Mixes\nSale Price: ₹261.0\nMarket Price: ₹290.0\nRating: 4.0 / 5.0\nDescription: Wheatgrass is a superfood potent health food with amazing benefits. It contains all minerals, Vitamins A, B- complex, C, E, I and K. It is extremely rich in protein and contains 17 amino acids. It is thought to benefit health only when fresh and taken on an empty stomach immediately after being mixed.'),
 Document(metadata={'product': 'Butter Cookies Gold Collection', 'brand': 'Sapphire', 'category': 'Gourmet & World Food', 'sub_category': 'Chocolates & Biscuits', 'type': 'Luxury Chocolates, Gifts', 'sale_price': 600.0, 'market_price': 600.0, 'rating': 2.2, 'category_tag': 'Gourmet & World Food > Chocolates & Biscuits'}, page_content='Product: Butter Cookies Gold Collection\nBrand: Sapphire\nCategory: Gourmet & World Food > Chocolates & Biscuits\nType: Luxury Chocolates, Gifts\nSale Price: ₹600.0\nMarket Price: ₹600.0\nRating: 2.2 / 5.0\nDescription: Enjoy a tin full of delicious butter cookies made with pure Danish recipe. Enjoy them as an energy snack. or with tea and coffee. Sapphire Butter cookies make a perfect gift pack for your loved ones. This product is 100% vegetarian.'),
 Document(metadata={'product': 'Face Wash - Oil Control, Active', 'brand': 'Oxy', 'category': 'Beauty & Hygiene', 'sub_category': 'Skin Care', 'type': 'Face Care', 'sale_price': 110.0, 'market_price': 110.0, 'rating': 5.0, 'category_tag': 'Beauty & Hygiene > Skin Care'}, page_content='Product: Face Wash - Oil Control, Active\nBrand: Oxy\nCategory: Beauty & Hygiene > Skin Care\nType: Face Care\nSale Price: ₹110.0\nMarket Price: ₹110.0\nRating: 5.0 / 5.0\nDescription: This face wash deeply cleanses dirt and impurities. Active ingredients help remove excess oil and other pimple causing germs, leaving skin clean and fresh. Its a oil-control & pimple clearing ingredients which rid your skin of excess oil and other a pimple-causing germs, leaving it clean and fresh.'),
 Document(metadata={'product': 'Mold & Mildew Remover with Bleach', 'brand': 'Clorox', 'category': 'Cleaning & Household', 'sub_category': 'All Purpose Cleaners', 'type': 'Floor & Other Cleaners', 'sale_price': 350.0, 'market_price': 350.0, 'rating': 3.8, 'category_tag': 'Cleaning & Household > All Purpose Cleaners'}, page_content='Product: Mold & Mildew Remover with Bleach\nBrand: Clorox\nCategory: Cleaning & Household > All Purpose Cleaners\nType: Floor & Other Cleaners\nSale Price: ₹350.0\nMarket Price: ₹350.0\nRating: 3.8 / 5.0\nDescription: This formula has been scientifically proven to kill 99.9% of germs. It removes mold & mildew powerfully, leaving no residue behind. cleans & disinfects at the same time. Colox Mold & Mildew Remover with Bleach is perfect for a solution for a germ-free house.'),
 Document(metadata={'product': 'Just Spray - Mosquito Repellent Room Spray', 'brand': 'Herbal Strategi', 'category': 'Cleaning & Household', 'sub_category': 'Fresheners & Repellents', 'type': 'Mosquito Repellent', 'sale_price': 200.0, 'market_price': 200.0, 'rating': 4.2, 'category_tag': 'Cleaning & Household > Fresheners & Repellents'}, page_content='Product: Just Spray - Mosquito Repellent Room Spray\nBrand: Herbal Strategi\nCategory: Cleaning & Household > Fresheners & Repellents\nType: Mosquito Repellent\nSale Price: ₹200.0\nMarket Price: ₹200.0\nRating: 4.2 / 5.0\nDescription: Strategi Just Spray is a very effective 100% Herbal Mosquito Repellent Room Spray completed from a distinctive mix of plant extracts and fragrant oils which remains mosquitoes away for 8-12 hrs. Just Spray has been developed to remove the discomfort of using chemical mosquito repellents such as chemical vaporisers, chemical mosquito coils etc.'),
 Document(metadata={'product': 'Dove Plastic Soap Case - Assorted Colour', 'brand': 'Nakoda', 'category': 'Cleaning & Household', 'sub_category': 'Bins & Bathroom Ware', 'type': 'Soap Cases & Dispensers', 'sale_price': 49.0, 'market_price': 59.0, 'rating': 4.0, 'category_tag': 'Cleaning & Household > Bins & Bathroom Ware'}, page_content='Product: Dove Plastic Soap Case - Assorted Colour\nBrand: Nakoda\nCategory: Cleaning & Household > Bins & Bathroom Ware\nType: Soap Cases & Dispensers\nSale Price: ₹49.0\nMarket Price: ₹59.0\nRating: 4.0 / 5.0\nDescription: This soap case is made of virgin plastic which makes it strong and durable. This is ideal for the bathroom, kitchen, etc.This will protect your soap bars from melting and will make it lasts longer.'),
 Document(metadata={'product': 'Smooth Skin Oil - For Dry Skin', 'brand': 'Aroma Treasures', 'category': 'Beauty & Hygiene', 'sub_category': 'Skin Care', 'type': 'Aromatherapy', 'sale_price': 324.0, 'market_price': 360.0, 'rating': 5.0, 'category_tag': 'Beauty & Hygiene > Skin Care'}, page_content='Product: Smooth Skin Oil - For Dry Skin\nBrand: Aroma Treasures\nCategory: Beauty & Hygiene > Skin Care\nType: Aromatherapy\nSale Price: ₹324.0\nMarket Price: ₹360.0\nRating: 5.0 / 5.0\nDescription: Specially crafted for dry skin, this richly formulated skin oil restores the natural moisture of the skin, improves its health and youthfulness. Not to mention how soft, shiny and smooth it makes your skin.\r\n\r\n\r\nAroma Treasures, pioneers of aromatherapy have put in years of research and study to give you the ultimate range of beauty care products.'),
 Document(metadata={'product': 'Salted Pumpkin', 'brand': 'Graminway', 'category': 'Gourmet & World Food', 'sub_category': 'Snacks, Dry Fruits, Nuts', 'type': 'Roasted Seeds & Nuts', 'sale_price': 180.0, 'market_price': 180.0, 'rating': 4.9, 'category_tag': 'Gourmet & World Food > Snacks, Dry Fruits, Nuts'}, page_content='Product: Salted Pumpkin\nBrand: Graminway\nCategory: Gourmet & World Food > Snacks, Dry Fruits, Nuts\nType: Roasted Seeds & Nuts\nSale Price: ₹180.0\nMarket Price: ₹180.0\nRating: 4.9 / 5.0\nDescription: Graminway Salted Pumpkin Seeds are the perfect snack for your family. These are ancient food, lost with time. These are tiny nutritional powerhouses loaded with essential elements, many of which are trace elements. They are rich in manganese, magnesium, copper, and zinc, which can give your health an added boost. Pumpkin seeds are the best sources of plant-based omega-3s (alpha-linolenic acid). Also, they are rich in healthy fats, antioxidants, and fibres. Moreover, they are easy to carry and make an excellent snack when you are on the go and can be a quick snack when you are home too. At Graminway, they believe that everyone deserves to live a full and healthy life. The intake of their food supplements will provide a good foundation for a healthy lifestyle. They are committed to providing the highest quality products at affordable price. They are a company with a purpose beyond profit and want to make a lasting difference in the world. Graminway aims to provide clean, natural, and healthy products without compromising on the flavours and taste. They produce them in small batches, which helps maintain freshness and preserve the ingredient texture. By not stockpiling, each product is as fresh as possible when it reaches your doorstep.'),

In [ ]:
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
import os

embedding_model = HuggingFaceEmbeddings(
    model_name="thenlper/gte-small",
    model_kwargs={"device": "cpu"}
)

vectorstore = FAISS.from_documents(docs, embedding_model)

vectorstore.save_local("vectorstore")

vectorstore = FAISS.load_local(vectorstore, embedding_model, allow_dangerous_deserialization=True)

query = "affordable skincare with high rating"
results = vectorstore.similarity_search(query, k=3)

for i, res in enumerate(results, 1):
    print(f"\nResult {i}:")
    print(res.page_content)
    print("Metadata:", res.metadata)

C:\Users\saipr\AppData\Local\Temp\ipykernel_23248\1505274759.py:4: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embedding_model = HuggingFaceEmbeddings(
c:\Users\saipr\BigBasket\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Result 1:
Product: Specialist Skin Care Oil - Scars, Stretch Mark, Ageing, Uneven Skin Tone
Brand: Bio-Oil
Category: Beauty & Hygiene > Mothers & Maternity
Type: Body Care
Sale Price: ₹560.0
Market Price: ₹700.0
Rating: 3.6 / 5.0
Description: Bio-Oil Skincare Oil is made for all skin types, this skincare oil can be used to help reduce the appearance of stretch marks, scars, and other marks due to surgery, injury, acne, aging, pregnancy, and more. Its fast-absorbing, non-comedogenic formula won't clog pores. It helps the skin to retain essential moisture to soften skin and provide dry skin relief. It's truly a multiuse oil that's recommended by skincare specialists across the world. Its unique formulation, which contains Vitamins and plant extracts along with the breakthrough ingredient PurCellin Oil™ is highly effective and clinically proven.
Metadata: {'product': 'Specialist Skin Care Oil - Scars, Stretch Mark, Ageing, Uneven Skin Tone', 'brand': 'Bio-Oil', 'category': 'Beauty & Hygiene', 'sub_category': 'Mothers & Maternity', 'type': 'Body Care', 'sale_price': 560.0, 'market_price': 700.0, 'rating': 3.6, 'category_tag': 'Beauty & Hygiene > Mothers & Maternity'}

Result 2:
Product: Specialist Skin Care Oil - Scars, Stretch Mark, Ageing, Uneven Skin Tone
Brand: Bio-Oil
Category: Beauty & Hygiene > Mothers & Maternity
Type: Body Care
Sale Price: ₹333.0
Market Price: ₹450.0
Rating: 4.2 / 5.0
Description: Bio-Oil Skincare Oil is made for all skin types, this skincare oil can be used to help reduce the appearance of stretch marks, scars, and other marks due to surgery, injury, acne, aging, pregnancy, and more. Its fast-absorbing, non-comedogenic formula won't clog pores. It helps the skin to retain essential moisture to soften skin and provide dry skin relief. It's truly a multiuse oil that's recommended by skincare specialists across the world. Its unique formulation, which contains Vitamins and plant extracts along with the breakthrough ingredient PurCellin Oil™ is highly effective and clinically proven.
Metadata: {'product': 'Specialist Skin Care Oil - Scars, Stretch Mark, Ageing, Uneven Skin Tone', 'brand': 'Bio-Oil', 'category': 'Beauty & Hygiene', 'sub_category': 'Mothers & Maternity', 'type': 'Body Care', 'sale_price': 333.0, 'market_price': 450.0, 'rating': 4.2, 'category_tag': 'Beauty & Hygiene > Mothers & Maternity'}

Result 3:
Product: Specialist Skin Care Oil - Scars, Stretch Mark, Ageing, Uneven Skin Tone
Brand: Bio-Oil
Category: Beauty & Hygiene > Skin Care
Type: Body Care
Sale Price: ₹560.0
Market Price: ₹700.0
Rating: 3.6 / 5.0
Description: Bio-Oil Skincare Oil is made for all skin types, this skincare oil can be used to help reduce the appearance of stretch marks, scars, and other marks due to surgery, injury, acne, aging, pregnancy, and more. Its fast-absorbing, non-comedogenic formula won't clog pores. It helps the skin to retain essential moisture to soften skin and provide dry skin relief. It's truly a multiuse oil that's recommended by skincare specialists across the world. Its unique formulation, which contains Vitamins and plant extracts along with the breakthrough ingredient PurCellin Oil™ is highly effective and clinically proven.
Metadata: {'product': 'Specialist Skin Care Oil - Scars, Stretch Mark, Ageing, Uneven Skin Tone', 'brand': 'Bio-Oil', 'category': 'Beauty & Hygiene', 'sub_category': 'Skin Care', 'type': 'Body Care', 'sale_price': 560.0, 'market_price': 700.0, 'rating': 3.6, 'category_tag': 'Beauty & Hygiene > Skin Care'}

In [11]:
from langchain_groq import ChatGroq 
import os
os.environ['GROQ_API_KEY']=os.getenv('GROQ_API_KEY')
llm = ChatGroq(model_name="llama-3.3-70b-versatile")

In [ ]:
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
import os

main_folder = os.getcwd()
save_path = os.path.join(main_folder, "vectorstore")

embedding_model = HuggingFaceEmbeddings(
    model_name="thenlper/gte-small",
    model_kwargs={"device": "cpu"}
)

vectorstore = FAISS.from_documents(docs, embedding_model)

vectorstore.save_local(save_path)

vectorstore = FAISS.load_local(save_path, embedding_model, allow_dangerous_deserialization=True)

query = "affordable skincare with high rating"
results = vectorstore.similarity_search(query, k=3)
for i, res in enumerate(results, 1):
    print(f"\nResult {i}:")
    print(res.page_content)
    print("Metadata:", res.metadata)

KeyboardInterrupt: